<?php

namespace DirectoryPlatform\AppBundle\Repository;

/**
 * EmailTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplateRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByPublished($request)
    {
        $filterKey = $request->get('emailKey');
        $filterSubject = $request->get('subject');
        $filterActive = $request->get('isActive');
        $filterArchived = $request->get('isArchived');
        
        $qb = $this->createQueryBuilder('emailtemplate');
        
        if($filterKey != ''){    
            $qb->andWhere('emailtemplate.emailKey LIKE :filterKey')
                 ->setParameter('filterKey','%'.$filterKey.'%');
        }
        if($filterSubject != ''){    
            $qb->andWhere('emailtemplate.subject LIKE :filterSubject')
                 ->setParameter('filterSubject','%'.$filterSubject.'%');
        }

        if($filterActive != ''){

            if($filterActive == 0){
                $qb->andWhere('emailtemplate.isActive = :filterActive OR emailtemplate.isActive is NULL ');
            }else{
                $qb->andWhere('emailtemplate.isActive = :filterActive');
            }
            $qb->setParameter('filterActive', $filterActive);
        }

        if($filterArchived != ''){

            if($filterArchived == 0){
                $qb->andWhere('emailtemplate.isArchived = :filterArchived OR emailtemplate.isArchived is NULL ');
            }else{
                $qb->andWhere('emailtemplate.isArchived = :filterArchived');
            }
            $qb->setParameter('filterArchived', $filterArchived);
        }

        return  $qb->getQuery()
                  ->execute();
    }
}
