<?php

namespace DirectoryPlatform\AppBundle\Repository;

/**
 * NewslaterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewslaterRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByPublished($request)
    {
        $filterSubject = $request->get('Subject');
        $filterBody = $request->get('Body');
        $filterSentDate = $request->get('SentDate');
        $filterListActive = $request->get('Active');
        
        $qb = $this->createQueryBuilder('newslater')
        			->orderBy('newslater.created', 'DESC');
        
        if($filterSubject != ''){    
            $qb->andWhere('newslater.subject LIKE :filterSubject')
                 ->setParameter('filterSubject','%'.$filterSubject.'%');
        }
        if($filterBody != ''){    
            $qb->andWhere('newslater.body LIKE :filterBody')
                 ->setParameter('filterBody','%'.$filterBody.'%');
        }
        if($filterSentDate != ''){    
            $qb->andWhere('newslater.sentDate LIKE :filterSentDate')
                 ->setParameter('filterSentDate','%'.$filterSentDate.'%');
        }

        if($filterListActive != ''){
            if($filterListActive == 0){
                $qb->andWhere('newslater.isActive = :isActive OR newslater.isActive is NULL ');
            }else{
                $qb->andWhere('newslater.isActive = :isActive');
            }
            $qb->setParameter('isActive', $filterListActive);
        }
        return  $qb->getQuery()
                  ->execute();
    }
}
